engines:
  eslint:
    enabled: true
  csslint:
    enabled: true  
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_paths:
- "**/dist/**/*"
